version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/MileStone3
    overwrite: true
    file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/MileStone3
    pattern: "**"
    owner: ec2-user
    group: ec2-user    
hooks:
  BeforeInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/app_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: ec2-user
